# Generated by Django 3.1 on 2020-08-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('apellidopaterno', models.CharField(db_column='apellidoPaterno', max_length=20)),
                ('apellidomaterno', models.CharField(blank=True, db_column='apellidoMaterno', max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('telefonouno', models.CharField(blank=True, db_column='telefonoUno', max_length=15, null=True)),
                ('telefonodos', models.CharField(blank=True, db_column='telefonoDos', max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=45, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('codigopostal', models.CharField(blank=True, db_column='codigoPostal', max_length=15, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('email', models.CharField(db_column='email', max_length=150)),
            ],
        ),
    ]
