# Generated by Django 3.1 on 2020-08-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('idbanco', models.AutoField(db_column='idBanco', primary_key=True, serialize=False)),
                ('nombrebanco', models.CharField(db_column='nombreBanco', max_length=35)),
                ('telefonobanco', models.CharField(blank=True, db_column='telefonoBanco', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cabecerapedidos',
            fields=[
                ('idcabecerapedido', models.AutoField(db_column='idCabeceraPedido', primary_key=True, serialize=False)),
                ('fechapedido', models.DateTimeField(blank=True, db_column='fechaPedido', null=True)),
                ('fechaconfirmacion', models.DateTimeField(blank=True, db_column='fechaConfirmacion', null=True)),
                ('fechaentrega', models.DateTimeField(blank=True, db_column='fechaEntrega', null=True)),
                ('cargo', models.CharField(blank=True, db_column='Cargo', max_length=60, null=True)),
                ('destinatario', models.CharField(blank=True, db_column='Destinatario', max_length=60, null=True)),
                ('direcciondestinatario', models.CharField(blank=True, db_column='DireccionDestinatario', max_length=60, null=True)),
                ('ciudaddestinatario', models.CharField(blank=True, db_column='CiudadDestinatario', max_length=60, null=True)),
                ('regiondestinatario', models.CharField(blank=True, db_column='RegionDestinatario', max_length=60, null=True)),
                ('codpostaldestinatario', models.CharField(blank=True, db_column='CodPostalDestinatario', max_length=60, null=True)),
                ('paisdestinatario', models.CharField(blank=True, db_column='PaisDestinatario', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='nombreCategoria', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('apellidopaterno', models.CharField(db_column='apellidoPaterno', max_length=20)),
                ('apellidomaterno', models.CharField(blank=True, db_column='apellidoMaterno', max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, max_length=35, null=True)),
                ('telefonouno', models.CharField(blank=True, db_column='telefonoUno', max_length=15, null=True)),
                ('telefonodos', models.CharField(blank=True, db_column='telefonoDos', max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('codigopostal', models.CharField(blank=True, db_column='codigoPostal', max_length=15, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('iddelivery', models.AutoField(db_column='idDelivery', primary_key=True, serialize=False)),
                ('nombredelivery', models.CharField(db_column='nombreDelivery', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('dnidelivery', models.CharField(blank=True, db_column='dniDelivery', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.IntegerField(db_column='idProveedor', primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(db_column='nombreEmpresa', max_length=60)),
                ('rucempresa', models.CharField(blank=True, db_column='rucEmpresa', max_length=15, null=True)),
                ('direccionempresa', models.CharField(blank=True, db_column='direccionEmpresa', max_length=60, null=True)),
                ('sucursalempresa', models.CharField(blank=True, db_column='sucursalEmpresa', max_length=15, null=True)),
                ('telefonoempresa', models.CharField(blank=True, db_column='telefonoEmpresa', max_length=15, null=True)),
                ('emailempresa', models.CharField(blank=True, db_column='emailEmpresa', max_length=35, null=True)),
                ('nombrecontacto', models.CharField(blank=True, db_column='nombreContacto', max_length=35, null=True)),
                ('telefonocontactouno', models.CharField(blank=True, db_column='telefonoContactoUno', max_length=15, null=True)),
                ('telefonocontactodos', models.CharField(blank=True, db_column='telefonoContactoDos', max_length=15, null=True)),
                ('emailcontacto', models.CharField(blank=True, db_column='emailContacto', max_length=35, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='nombreProducto', max_length=40)),
                ('presentacion', models.CharField(blank=True, max_length=50, null=True)),
                ('preciounidad', models.DecimalField(blank=True, db_column='precioUnidad', decimal_places=2, max_digits=10, null=True)),
                ('unidadesenexistencia', models.SmallIntegerField(blank=True, db_column='unidadesEnExistencia', null=True)),
                ('unidadesenpedido', models.SmallIntegerField(blank=True, db_column='unidadesEnPedido', null=True)),
                ('fechacompra', models.DateField(blank=True, db_column='fechaCompra', null=True)),
                ('fechaexpiracion', models.DateField(blank=True, db_column='fechaExpiracion', null=True)),
                ('costoestimado', models.DecimalField(blank=True, db_column='costoEstimado', decimal_places=2, max_digits=10, null=True)),
                ('srcimagen', models.CharField(blank=True, db_column='srcImagen', max_length=100, null=True)),
                ('suspendido', models.SmallIntegerField(blank=True, null=True)),
                ('idcategoria', models.ForeignKey(blank=True, db_column='idCategoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.categorias')),
                ('idproveedor', models.ForeignKey(blank=True, db_column='idProveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idempleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('apellidopaterno', models.CharField(blank=True, db_column='apellidoPaterno', max_length=20, null=True)),
                ('apellidomaterno', models.CharField(blank=True, db_column='apellidoMaterno', max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, max_length=35, null=True)),
                ('dni', models.CharField(max_length=15)),
                ('fechanacimiento', models.DateField(blank=True, db_column='FechaNacimiento', null=True)),
                ('fechacontratacion', models.DateField(blank=True, db_column='FechaContratacion', null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=15, null=True)),
                ('region', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, db_column='telefonoFijo', max_length=15, null=True)),
                ('telefonomovil', models.CharField(blank=True, db_column='telefonoMovil', max_length=15, null=True)),
                ('numerocuentabancaria', models.CharField(blank=True, db_column='numeroCuentaBancaria', max_length=60, null=True)),
                ('sueldobasico', models.DecimalField(blank=True, db_column='sueldoBasico', decimal_places=2, max_digits=10, null=True)),
                ('descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('idbanco', models.ForeignKey(blank=True, db_column='idBanco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Detallepedidos',
            fields=[
                ('iddetallepedidos', models.AutoField(db_column='idDetallePedidos', primary_key=True, serialize=False)),
                ('preciounidad', models.DecimalField(db_column='precioUnidad', decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('idcabecerapedido', models.ForeignKey(blank=True, db_column='idCabeceraPedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.cabecerapedidos')),
                ('idproducto', models.ForeignKey(blank=True, db_column='idProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.productos')),
            ],
        ),
        migrations.AddField(
            model_name='cabecerapedidos',
            name='idcliente',
            field=models.ForeignKey(blank=True, db_column='idCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.clientes'),
        ),
        migrations.AddField(
            model_name='cabecerapedidos',
            name='iddelivery',
            field=models.ForeignKey(blank=True, db_column='idDelivery', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.delivery'),
        ),
        migrations.AddField(
            model_name='cabecerapedidos',
            name='idempleado',
            field=models.ForeignKey(blank=True, db_column='idEmpleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.empleados'),
        ),
    ]
