# Generated by Django 3.1 on 2020-08-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='nombreCategoria', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(db_column='idProveedor', primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(db_column='nombreEmpresa', max_length=60)),
                ('rucempresa', models.CharField(blank=True, db_column='rucEmpresa', max_length=15, null=True)),
                ('direccionempresa', models.CharField(blank=True, db_column='direccionEmpresa', max_length=60, null=True)),
                ('sucursalempresa', models.CharField(blank=True, db_column='sucursalEmpresa', max_length=15, null=True)),
                ('telefonoempresa', models.CharField(blank=True, db_column='telefonoEmpresa', max_length=15, null=True)),
                ('emailempresa', models.CharField(blank=True, db_column='emailEmpresa', max_length=35, null=True)),
                ('nombrecontacto', models.CharField(blank=True, db_column='nombreContacto', max_length=35, null=True)),
                ('telefonocontactouno', models.CharField(blank=True, db_column='telefonoContactoUno', max_length=15, null=True)),
                ('telefonocontactodos', models.CharField(blank=True, db_column='telefonoContactoDos', max_length=15, null=True)),
                ('emailcontacto', models.CharField(blank=True, db_column='emailContacto', max_length=35, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='nombreProducto', max_length=200)),
                ('presentacion', models.CharField(blank=True, max_length=50, null=True)),
                ('preciounidad', models.DecimalField(blank=True, db_column='precioUnidad', decimal_places=2, max_digits=10, null=True)),
                ('unidadesenexistencia', models.SmallIntegerField(blank=True, db_column='unidadesEnExistencia', null=True)),
                ('unidadesenpedido', models.SmallIntegerField(blank=True, db_column='unidadesEnPedido', null=True)),
                ('fechacompra', models.DateField(blank=True, db_column='fechaCompra', null=True)),
                ('fechaexpiracion', models.DateField(blank=True, db_column='fechaExpiracion', null=True)),
                ('costoestimado', models.DecimalField(blank=True, db_column='costoEstimado', decimal_places=2, max_digits=10, null=True)),
                ('srcimagen', models.CharField(blank=True, db_column='srcImagen', max_length=100, null=True)),
                ('suspendido', models.SmallIntegerField(blank=True, null=True)),
                ('idcategoria', models.ForeignKey(blank=True, db_column='idCategoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.categorias')),
                ('idproveedor', models.ForeignKey(blank=True, db_column='idProveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.proveedores')),
            ],
        ),
    ]
